FROM alpine:3.9

WORKDIR /root/

RUN apk add --force-refresh curl ca-certificates && \
    curl -SLO  https://github.com/alexellis/inlets/releases/download/0.5.2/inlets && \
    chmod +x inlets && \
    apk del curl

CMD ["./inlets"]
